### ISSUE TITLE
Fraktionisten Fahrzeug der Justiz

### ISSUE THREAD

**Issue by FynnLeDo2021** [DulliAG/A3RLRPG-Infopanel#6]
In der Garage werden Fahrzeuge der Fraktion "Justiz" als Zivilist angezeigt, ist die Frage ob das nur bei bei der Justiz so ist oder bei allen...

**Comment by tklein1801** [comment]
@FynnLeDo2021 gefixt?

**Comment by FynnLeDo2021** [comment]
Negativ

**Comment by FynnLeDo2021** [comment]
"data": [
        {
            "id": 774,
            "pid": "76561198306353032",
            "side": "WEST",
            "classname": "RL_BMW_M5_F11_justiz",
            "type": "Car",
            "plate": "JWJF9001",
            "active": 0,
            "impound": 0,
            "alarm": 0,
            "disabled": 0,
            "color": "[]",
            "inventory": "\"[]\"",
            "gear": "\"[[[],[]],[[],[]],[],[[],[]]]\"",
            "fuel": "0.999443",
            "fuelcargo": 0,
            "tuning_color": null,
            "tuning_array": "\"[]\"",
            "tuning_perm": 0,
            "hitpoints": "[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]",
            "kilometer": 5000,
            "kilometer_total": 0,
            "lastgarage": "cop_court",
            "alive": 1,
            "insurance": 0,
            "companyid": -1,
            "companytype": "NONE",
            "updated_at": "2022-05-27 19:05:27",
            "created_at": "2022-05-27 19:04:58",
            "vehicle_data": {
                "id": 1159,
                "classname": "RL_BMW_M5_F11_justiz",
                "name": "BMW M5 F11 Justiz",
                "price": 800000,
                "level": 3,
                "v_space": 60,
                "shoptype": "justiz_car",
                "shopname": "Justiz - Fahrzeuge",
                "type": "Car"
            },
            "export_vehicles": [
                {
                    "id": 1159,
                    "classname": "RL_BMW_M5_F11_justiz",
                    "name": "BMW M5 F11 Justiz",
                    "price": 800000,
                    "level": 3,
                    "v_space": 60,
                    "shoptype": "justiz_car",
                    "shopname": "Justiz - Fahrzeuge",
                    "type": "Car"
                }
            ]
        },

**Comment by tklein1801** [comment]
@FynnLeDo2021Build war nicht erfolgreich. Kannste mal schauen?
Ich habe auf die [offizielle Lösung](https://github.com/A3ReallifeRPG/RealLifeRPG-App/blob/a9dd7832ae100c77ad8b30d0b4a6f340639ea894/app/src/main/java/de/realliferpg/app/helper/FractionMappingHelper.java#L46) zurückgegriffen

**Comment by FynnLeDo2021** [comment]
Jaaa geht doch xD

**Comment by tklein1801** [comment]
Danke sehr :)
